### ISSUE TITLE
Kitchen Preferences

### ISSUE THREAD

**Issue by GeorgeHartle** [Syzl-io/issues#12]
**Is your feature request related to a problem? Please describe.**
No "confirm" button to take you to next preference type

**Describe the solution you'd like**
Add "confirm" button to take you to next preference type, then a "save" button for the last one to take you back to your account maybe?

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by ShannonT13** [comment]
Issue has been resolved.
