### ISSUE TITLE
Account creation

### ISSUE THREAD

**Issue by AdamProfilio** [Syzl-io/issues#15]
**Describe the bug**
Screen not scaling on Android

**To Reproduce**
1. Go through process
2. Get to email step
3. See page not scaling

**Expected behavior**
Screen content to scale for mobile

**Screenshots**
![3ed607bc-3cfc-4cae-a8df-af5bcbcff23d](https://user-images.githubusercontent.com/106273330/170349701-6d65fa78-d537-422b-8d67-f549fae12e0a.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android 12
 - Browser Chrome
 - Version 101.0.4951.61

**Comment by ShannonT13** [comment]
Issue has been resolved.

**Comment by jason-raiin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Download application button missing](https://trello.com/c/omobLQXC/1724-download-application-button-missing)
