### ISSUE TITLE
Kitchen Booking

### ISSUE THREAD

**Issue by GeorgeHartle** [Syzl-io/issues#16]
**Describe the bug**
Won't allow booking to be made due to popup of random number.

**To Reproduce**
1. Go through booking process
2. Be shown popup as you click "book"

**Expected behavior**
Booking would be made

**Screenshots**
![Image from iOS](https://user-images.githubusercontent.com/18281325/170351089-52268499-e407-4e97-86d6-ef8247d7fd09.png)

**Desktop (please complete the following information):**
-

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 15.5
 - Browser Chrome
 - Version 102.0.5005.67

**Additional context**
-

**Comment by JustACodeMonkey** [comment]
Fixed - Bad math in JavaScript
