### ISSUE TITLE
Book another kitchen

### ISSUE THREAD

**Issue by GeorgeHartle** [Syzl-io/issues#17]
**Describe the bug**
No way to select any dates

**To Reproduce**
1. Go to book a kitchen
2. Try to select dates
3. Can't select any dates

**Expected behavior**
Ability to be able to select dates

**Screenshots**
-

**Desktop (please complete the following information):**
-

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: IOS 15.5
 - Browser Chrome
 - Version 102.0.5005.67

**Additional context**
-

**Comment by ShannonT13** [comment]
Issue has been resolved.  Future enhancements.
