### ISSUE TITLE
Kitchen listings

### ISSUE THREAD

**Issue by AdamProfilio** [Syzl-io/issues#19]
**Describe the bug**
Listing page isn't scaling to my browser

**Screenshots**
![image](https://user-images.githubusercontent.com/106273330/170355454-9a7bf8b4-87d9-4d97-9a8e-668e6615b717.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android 12
 - Browser Chrome
 - Version 101.0.4951.61

**Comment by ShannonT13** [comment]
Issue has been resolved.
