### ISSUE TITLE
IMPROVEMENT POINT: Confusing Picture Upload icon

### ISSUE THREAD

**Issue by mikehesyzl** [Syzl-io/issues#7]
![image](https://user-images.githubusercontent.com/103547274/164548216-7fac85ad-f23d-4a3d-943e-a02b69acbf7d.png)
Hard to grasp the difference between this picture upload icon and the "Gallery" section underneath in the kitchen creation tab.

**Comment by ShannonT13** [comment]
Issue resolved.  Labelling added.
