### ISSUE TITLE
Link on terms upon account creation

### ISSUE THREAD

**Issue by GeorgeHartle** [Syzl-io/issues#9]
**Is your feature request related to a problem? Please describe.**
Double up on the word "terms"

**Describe the solution you'd like**
Perhaps just link the first "terms" rather than adding a second

**Describe alternatives you've considered**
Put the link underneath rather than inline and make it something like "read here" or "read terms here"

**Additional context**
-

**Comment by ShannonT13** [comment]
Completed.
